#Disk space utilization inputs
#=============================
#Enter the path where logs are saved
log_path="/opt/product/testteam/Products"

#Enter the path where all the instances directories are available
Instance_parent_path="/opt/product/testteam/Products/NSSLOAD/DATALOAD/";

#Enter the minimum space ((in Gigabytes)that should be available before running load
log_path_min_size_Gb="40"

#Enter the maximum limit (in Gigabytes) of the load log folder, beyond which the
#log files will be deleted.
log_path_max_size_Gb="50"

#End of disk space utilization input
#=================================

#Number of attempts to retry if the application is not starting.
#Note:Entering higher value is not advisable. optimal value is 3.
restart_limit=3

#Enter the path where tcap_measurements, statistics, and load reports are generated.
load_report_path="/opt/product/testteam/Products/NSSLOAD/DATALOAD/LOAD_SCRIPTS/LOAD-REPORTS";

#Number of log/tdr files to be left after auto deletion
#Eg: If keep_files=10 then only 10 log/tdr files will be kept, rest will be deleted.
keep_files=50

#Number of log/tdr files to be left after auto gzip 
#Eg: If keep_zip_files=10 then only 10 log/tdr files will be kept, rest will be gzipped.
keep_unzip_files=10

#Time interval (delay) between starting products
lag=10

#Path where momque files are genereated
momq_path="/opt/ulcm/solaris6/tmp/";

#If the application goes down, should it be restarted.
# 0 dont restart
# 1 restart
restart_flag=1;

#If application goes save its logs.
#specify how many latest logs should be saved.
#example value 10 will save last 10 logs generated by the Application
sos_logs=10;
#Enter the product name
Server_Name=84SERVER
disk_partition_count=17
product_name_1=DNG;
#########################################

###### Instance 1 ###################
product_1[1]="dngServer-1";
product_path_1[1]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[1]="run1.sh";
product_log_1[1]="/cdr/DNG/LOGGER1/DNG_DL1_1";
product_move_log_to_1[1]="/logger/DNG_RRBS";
product_logicalname_1[1]="DNG001";
stack_1[1]="Stack1";
#####################################

###### Instance 2 ###################
product_1[2]="dngServer-2";
product_path_1[2]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[2]="run2.sh";
product_log_1[2]="/cdr/DNG/LOGGER2/DNG_DL2_2";
product_move_log_to_1[2]="/logger/DNG_RRBS";
product_logicalname_1[2]="DNG002";
stack_1[2]="Stack1";
#####################################


###### Instance 3 ###################
product_1[3]="dngServer-3";
product_path_1[3]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[3]="run3.sh";
product_log_1[3]="/cdr/DNG/LOGGER3/DNG_DL3_3";
product_move_log_to_1[3]="/logger/DNG_RRBS";
product_logicalname_1[3]="DNG003";
stack_1[3]="Stack1";
#####################################


###### Instance 4 ###################
product_1[4]="dngServer-4";
product_path_1[4]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[4]="run4.sh";
product_log_1[4]="/cdr/DNG/LOGGER4/DNG_DL4_4";
product_move_log_to_1[4]="/logger/DNG_RRBS";
product_logicalname_1[4]="DNG004";
stack_1[4]="Stack1";
#####################################


###### Instance 5 ###################
product_1[5]="dngServer-5";
product_path_1[5]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[5]="run5.sh";
product_log_1[5]="/cdr/DNG/LOGGER5/DNG_DL5_5";
product_move_log_to_1[5]="/logger/DNG_RRBS";
product_logicalname_1[5]="DNG005";
stack_1[5]="Stack1";
#####################################


###### Instance 6 ###################
product_1[6]="dngServer-6";
product_path_1[6]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[6]="run6.sh";
product_log_1[6]="/cdr/DNG/LOGGER6/DNG_DL6_6";
product_move_log_to_1[6]="/logger/DNG_RRBS";
product_logicalname_1[6]="DNG006";
stack_1[6]="Stack1";
#####################################


###### Instance 7 ###################
product_1[7]="dngServer-7";
product_path_1[7]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[7]="run7.sh";
product_log_1[7]="/cdr/DNG/LOGGER7/DNG_DL7_7";
product_move_log_to_1[7]="/logger/DNG_RRBS";
product_logicalname_1[7]="DNG007";
stack_1[7]="Stack1";
#####################################


###### Instance 8 ###################
product_1[8]="dngServer-8";
product_path_1[8]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DNG/bin";
product_start_1[8]="run8.sh";
product_log_1[8]="/cdr/DNG/LOGGER8/DNG_DL8_8";
product_move_log_to_1[8]="/logger/DNG_RRBS";
product_logicalname_1[8]="DNG008";
stack_1[8]="Stack1";
#####################################

####################################################################################################################################################
#########DNG-RRBS Dependent Product#################
product_name_2=PCRF-RRBS;
####################################

###### Instance 1 ###################
product_2[1]="rrbs_pcrf_1";
product_path_2[1]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/RRBS/release/bin";
product_start_2[1]="run1.sh 1 ../config";
product_log_2[1]="/logger/DNG_RRBS/LOGGER1";
product_move_log_to_2[1]="/cdr/DNG_RRBS";
product_logicalname_2[1]="rrbs";
stack_2[1]="Stack1";
#####################################
###### Instance 2 ###################
product_2[2]="rrbs_pcrf_2";
product_path_2[2]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/RRBS/release/bin";
product_start_2[2]="run2.sh 2 ../config";
product_log_2[2]="/logger/DNG_RRBS/LOGGER2";
product_move_log_to_2[2]="/cdr/DNG_RRBS";
product_logicalname_2[2]="rrbs";
stack_2[2]="Stack2";
#####################################

####################################################################################################################################################
#########DNG-RRBS Dependent Product#################
product_name_3=DNG-RRBS;
#####################################
###### Instance 1 ###################
product_3[1]="rrbs_dng_1";
product_path_3[1]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/RRBS/release/bin";
product_start_3[1]="run3.sh 3 ../config";
product_log_3[1]="/logger/DNG_RRBS/LOGGER3";
product_move_log_to_3[1]="/cdr/DNG_RRBS";
product_logicalname_3[1]="rrbs";
stack_3[1]="Stack3";
#####################################
###### Instance 2 ###################
product_3[2]="rrbs_dng_2";
product_path_3[2]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/RRBS/release/bin";
product_start_3[2]="run4.sh 4 ../config";
product_log_3[2]="/logger/DNG_RRBS/LOGGER4";
product_move_log_to_3[2]="/cdr/DNG_RRBS";
product_logicalname_3[2]="rrbs";
stack_3[2]="Stack4";
#####################################
###### Instance 3 ###################
product_3[3]="rrbs_dng_3";
product_path_3[3]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/RRBS/release/bin";
product_start_3[3]="run5.sh 5 ../config";
product_log_3[3]="/logger/DNG_RRBS/LOGGER5";
product_move_log_to_3[3]="/cdr/DNG_RRBS";
product_logicalname_3[3]="rrbs";
stack_3[3]="Stack5";
#####################################
###### Instance 4 ###################
product_3[4]="rrbs_dng_4";
product_path_3[4]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/RRBS/release/bin";
product_start_3[4]="run6.sh 6 ../config";
product_log_3[4]="/logger/DNG_RRBS/LOGGER6";
product_move_log_to_3[4]="/cdr/DNG_RRBS";
product_logicalname_3[4]="rrbs";
stack_3[4]="Stack6";

####################################################################################################################################################

#Enter the product name
#########PCRF Product#################
product_name_4=PCRF;
###### PCRF Instance 1 ###################
product_4[1]="PCRFLOAD1";
product_path_4[1]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/PCRF/release/bin";
product_start_4[1]="run1.sh 1 ../config";
product_log_4[1]="/opt/product/PCRFLOG/LOGGER1";
product_move_log_to_4[1]="/logger/PCRF";
product_logicalname_4[1]="PCRFLOAD";
stack_4[1]="Stack2";

###### PCRF Instance 2 ###################
product_4[2]="PCRFLOAD2";
product_path_4[2]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/PCRF/release/bin";
product_start_4[2]="run2.sh 2 ../config";
product_log_4[2]="/opt/product/PCRFLOG/LOGGER2";
product_move_log_to_4[2]="/logger/PCRF";
product_logicalname_4[2]="PCRFLOAD2";
stack_4[2]="Stack2";

###### PCRF Instance 3 ###################
product_4[3]="PCRFLOAD3";
product_path_4[3]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/PCRF/release/bin";
product_start_4[3]="run3.sh 3 ../config";
product_log_4[3]="/opt/product/PCRFLOG/LOGGER3";
product_move_log_to_4[3]="/logger/PCRF";
product_logicalname_4[3]="PCRFLOAD3";
stack_4[3]="Stack2";

###### PCRF Instance 4 ###################
product_4[4]="PCRFLOAD4";
product_path_4[4]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/PCRF/release/bin";
product_start_4[4]="run4.sh 4 ../config";
product_log_4[4]="/opt/product/PCRFLOG/LOGGER4";
product_move_log_to_4[4]="/logger/PCRF";
product_logicalname_4[4]="PCRFLOAD4";
stack_4[4]="Stack2";

####################################################################################################################################################
#########DIAMETRIQ STACK#################
product_name_5=DIASTCK-DNG;
####################################
###### Instance 1 ###################
product_5[1]="Dia_DNG";
product_path_5[1]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DIAMETRIQ-STACK/DNG_DIASTACK/release/bin";
product_start_5[1]="run.sh";
product_log_5[1]="/cdr/DIASTACK/DNGLOGGER";
product_move_log_to_5[1]="/cdr/DNG_RRBS";
product_logicalname_5[1]="stack001";
stack_5[1]="Stack2";
#####################################

####################################################################################################################################################
#########DIAMETRIQ STACK#################
product_name_6=DIASTCK-PCRF;
####################################

###### Instance 2 ###################
product_6[1]="Dia_PCRF";
product_path_6[1]="/opt/product/testteam/Products/NSSLOAD/DATALOAD/DIAMETRIQ-STACK/PCRF_DIASTACK/release/bin";
product_start_6[1]="run2.sh";
product_log_6[1]="/cdr/DIASTACK/PCRFLOGGER";
product_move_log_to_6[1]="/cdr/DNG_RRBS";
product_logicalname_6[1]="stack002";
stack_6[1]="Stack2";
####################################
####################################################################################################################################################

product_name_7=DNGSNMP;
#########################################

###### Instance 1 ###################
product_7[1]="gsnmpagent";
product_path_7[1]="/opt/product/testteam/Products/NSSLOAD/GENUTIL/gsnmp/bin";
product_start_7[1]="run.sh";
product_log_7[1]="/logger/SNMP_LOGGER/Glog/GUTIL_SNMP_GUT_1";
product_logicalname_7[1]="LOAD_GSNMP";
stack_7[1]="Stack1";
#####################################
####################################################################################################################################################

product_name_8=DAF;
#########################################

###### Instance 1 ###################
product_8[1]="dafagent";
product_path_8[1]="/opt/product/testteam/Products/NSSLOAD/GENUTIL/daf/bin";
product_start_8[1]="run.sh";
product_log_8[1]="/logger/SNMP_LOGGER/daflog/GUTIL_DAF_GUT_DAF_1";
product_logicalname_8[1]="LOAD_GSNMP";
stack_8[1]="Stack1";
#####################################

