#!/usr/bin/bash
############################################################################################################
#Product: Load Helper Script
#Version: 1.0.0.4
#Author : Arun Kumar
#License: Plintron Global Technology
#
#INFORMATION:
#-----------
#This script will read input from the loadconfg.sh file.
#It can calculate the disk space used and clean up.
#It can run any number of instances and products as configured in the loadconfg.sh file.
#It can maintain log files generated by application by either zip or  delete.
#It can capture the tcap measurements and memory utilizations
#It also monitors the applications and restarts them if dead.
#It generates hourly and minutes based statistics report.
#The report is also generated in CSV file for ease of viewing in windows system
#It writes a report which contains data about any abnormality occurences. i.e application restart etc..
#
#WARNING:
#--------
#Editing this file is strictly not advisable.
#
############################################################################################################
#Version 1.0.0.2 changes:
#-----------------------
#Included "move" option for log handling
#This will move logs to destination folder if the minimum logs to be maintained exceeds.
#Error will be thrown if no log path or invalid path is defined in configuration file and user selects move option
#Version 1.0.0.3 changes:
#-----------------------
#Included stop_load.sh to stop the script apart from ctrl+c
#If the script is not responding for ctrl+c then run this script
#Version 1.0.0.4 changes:
#-----------------------
# Bug fixing
#Version 1.0.0.5 changes:
#-----------------------
#Server stats, Instances stats and TcapMeasurements is now implemented for all
#products (main + dependent products). Its up to the user to enable and 
#disable during startup
##############################################################################################################



parent=$$
clear;
curr_path=`pwd`;
t=`date +%Y_%b_%d_%H_%M_%S`;
mom_occurance=1
#source the configuration file
if [ $# -ge 1 ]
then
   grep 'sos_logs' $1 >/dev/null 
   if [ $? -eq 0 ]
   then
      . $1
   else
      echo "Invalid file: $1 ";
      exit;
   fi
else 
. dataloadconfnew.sh
fi
echo "===============================================";
echo "Welcome. This is a generalized LOAD SCRIPT";
echo "=================================================";

disk_enable_input () {

	echo -n "Do you want to view the top 10 folders thats occupying the disk space [y/n]: "
	read disk_handle;
	if [ $disk_handle = "y" -o $disk_handle = "Y"  -o $disk_handle = "n" -o $disk_handle = "N" ] 2>/dev/null
	then
		:
	else
		echo "Invalid Entry";
		disk_enable_input;
	fi
	}
disk_enable_input;

#Disk space handling

if [ $disk_handle = "y" -o $disk_handle = "Y" ]
then

rm -rf tmp;
#################Checking the disk space for log folder########################
[[ ! -d $log_path ]] && echo "folder $log_path doesnt exists" && exit;
curr_path=`pwd`;
#convert Gb to Kb
log_path_min_size=`expr $log_path_min_size_Gb \* 1048576`
log_path_max_size=`expr $log_path_max_size_Gb \* 1048576`

actual_avail=`df -k $log_path | grep "%" | awk {'print $4'}`;

#convert KB to Gb
actual_avail_Gb=`df -h $log_path | grep "%" | awk {'print $4'}`;
top_10 () {
actual_avail=`df -k $log_path | grep "%" | awk {'print $4'}`;
actual_avail_Gb=`df -h $log_path | grep "%" | awk {'print $4'}`;
if [ $actual_avail -lt $log_path_min_size ]
then
   echo "Space $actual_avail_Gb avaliable is less than expected $log_path_min_size_Gb Gigabytes"
   parent_dir=`df -k $log_path | grep "%" | awk {'print $6'}`;
   echo "Calculating Top 10 folders which occupy most of the space...
This may take a while... (average time taken is: 15 to 30 Sec) Pls wait...
It takes longer time if the server is heavily occupied by some other Process/Application.."
   du -o $parent_dir | sort -n -r | head -10 | awk {'print $2'} > tmp;
   cat tmp | xargs  du -sh > tmp_size;
i=0;
echo "";
while read line
do
echo "$i)  $line";
i=`expr $i + 1`;
done < tmp_size
rm tmp_size;
raw_del_list=(`cat tmp`);
unset del_list[*];

selected_delete () {
echo -n "From the above list, enter how many folders do you want to delete: "
read nof;

case $nof in
[0-9]|[0-9][0-9])
                 [[ $nof -gt 10 ]] && echo "Out of range" && selected_delete;;
*) echo "invalid entry"; selected_delete;;
esac

i=0;
while [ $i -lt $nof ]
do
  echo -n "`expr $i + 1`. Enter the corresponding folder number from the above list : "
  read a;
  case $a in
  [0-9])
       del_list[$i]=${raw_del_list[ $a ]};;
  *) echo "invalid entry"; selected_delete;;
  esac
  i=`expr $i + 1`;
done

clear;
echo "You have choosen to delete the following directory contents :"
echo "";
for b in ${del_list[*]}
do
  echo $b;
done
echo "";
echo -n "Are you sure you want to clear the contents of the above directory? [y/n] : ";
read yn
if [ $yn != "y" -o $yn != "y" ]
then
  echo "ok Good Bye !!!" ;
   exit;
fi
}

delete () {
for b in ${del_list[*]}
do
echo "Clearing contents of  $b";
echo "This may take a while..";
cd $b
rm -f *.log*
rm -f *.tdr*
rm -f *.cdr*
cd $curr_path;
done
}

clear_contents () {

echo ""; echo "";

echo "what do you want to perform?
1. Clear contents of all the above listed directories
2. Clear contents of only selected directories
3. Do nothing, proceed as such
4. Quit the session
"
echo -n "Enter your choice: "
read choice
export flag=0;
case $choice in
1)
echo -n "Are you sure you want to clear the contents all the above directories? [y/n] : ";
read yn
if [ $yn != "y" -o $yn != "y" ]
then
  echo "ok Good Bye !!!" ;
   exit;
fi
del_list=(`cat tmp`);
delete;
unset del_list[*];;
2)
  selected_delete;
  delete;;
3)
export flag=1;
break 2>/dev/null ;;
4)exit;;
*)echo "Invalid entry"; clear_contents;;
esac
}
clear_contents;
else
echo -e "Sufficient space available. Space $actual_avail_Gb avaliable while expected is $log_path_min_size_Gb Gigabytes \n"
fi
}
top_10;
while [ $flag != 1 ] 2>/dev/null
do
actual_avail=`df -k $log_path | grep "%" | awk {'print $4'}`;
while [ $actual_avail -lt $log_path_min_size ]
do
echo -e "\n \n";
echo "Cleaning the top 10 folders didnt help... Lets do it again..";
top_10;
actual_avail=`df -k $log_path | grep "%" | awk {'print $4'}`;
done
actual_avail_Gb=`df -h $log_path | grep "%" | awk {'print $4'}`;
echo -e "Sufficient space available. Space $actual_avail_Gb avaliable while expected is $log_path_min_size_Gb Gigabytes \n"
break;
done
rm tmp 2>/dev/null;
clear
fi
############################### end of disk space validation ##################################################

main_load="unknown_prodcut";

#validation for load_report_path
if [ -d $load_report_path ] 
then
	:
else
	echo "Invalid path. load_report_path= $load_report_path";
	exit;
fi



#function for ctrl+c handling
ppid=$$
stop_pr () {
	echo 
	echo "Signal Ctrl+C received. Load Script is going down...";
	grep -i "MOM" $load_report_path/${main_load}_OneMinute_Statistics_${t}.log 2>/dev/null | grep -v MOMQUE >/dev/null 2>/dev/null
	mom_occurance=$?;
	if [ $mom_occurance -eq 0 ]
	then
		echo "###############################################"
		echo "MOM was observed. Pls check the logs at $momq_path/$momque";
                echo "###############################################"
                echo "###############################################" >> $load_report_path/Load_Report_$main_load-$t.txt
		echo "MOM was observed. Pls check the logs at $momq_path/$momque" >> $load_report_path/Load_Report_$main_load-$t.txt
                echo "###############################################" >> $load_report_path/Load_Report_$main_load-$t.txt
		echo "MOM was observed. Pls check the logs at $momq_path/$momque" >> $load_report_path/${main_load}_Hourly_Mem_CPU_${t}.csv
		echo "MOM was observed. Pls check the logs at $momq_path/$momque" >> $load_report_path/${main_load}_Minutes_Mem_CPU_${t}.csv
	fi
	echo "Signal Ctrl+C received. Load Script is going down..." >> $load_report_path/Load_Report_$main_load-$t.txt
        echo "" >> $load_report_path/Load_Report_$main_load-$t.txt
	echo "================================" >> $load_report_path/Load_Report_$main_load-$t.txt
	echo "Load ended at $(date)" >> $load_report_path/Load_Report_$main_load-$t.txt
	echo "================================" >> $load_report_path/Load_Report_$main_load-$t.txt
        cat .lockfile 2>/dev/null &
        echo > .lockfile
	rm -rf .lockfile	
        echo "the pids are ${exec_order[@]} "
	for i in "${exec_order[@]}"
	do
  		for j in {1..90}
  		do
  			eval m=\$product_name_$j
    			if [ "$i" == "$m" ]
    			then
				eval total_instances=\${inital_inst_pid_$j[@]};
				echo "Bringing down all the instances of the product $m...."; 
				echo "Process ids: $total_instances";
				kill -2 $total_instances 2>/dev/null
                kill -9 $total_instances 2>/dev/null
			fi
		done
	done

	for i in `ps -ef| awk '$3 == '${ppid}' { print $2 }'`
	do
		echo "Stopping the child process $i";
		kill -9 $i 2>/dev/null
	done
	echo "Bringing down the main script $0 with process id: $ppid";
	kill -2 $ppid;
        kill -9 $ppid;
}

rm -rf .lockfile
mkfifo .lockfile

stop_load () {
cmd=`cat .lockfile`
if [ "$cmd" == "end" ]
then
   rm -rf .lockfile
   kill -2 $parent
fi
}

trap 'stop_pr' 2
#computing total number of available products and displaying it to user
for i in {1..90}
do

  eval j=\${#product_$i[*]};

  if [ $j -eq 0 ] 
  then
      total_product=`expr $i - 1`;
      break;
  fi

done
echo ""; echo "";
echo  "Totally $total_product products found."
echo ""; echo "";
echo "S.No  Product Name"
echo "====  ============ ";
echo ; 

for (( i=1; i<=$total_product; i++ )) 
do
  eval disp_pname=\$product_name_$i
  echo " $i     $disp_pname"; 
  product_array[$i]=$disp_pname;
done

echo ;



#subroutine for user input handling. Enter the main product
enter_main_prdct () {
	echo -n "Enter the main product's S.No: "
	read k1;
	if [ $k1 -le $total_product -a $k1 -gt 0 ] 2>/dev/null
	then
		:
	else
                echo "Invalid Entry";
		enter_main_prdct;
	fi
}
enter_main_prdct;
eval main_pname=\$product_name_$k1
echo "You have selected $main_pname as main product.";

#Creating load_report_path  new folder with product name and time stamp 
dat1=`date +%F_%H_%M_%S`;
new_folder="Load_$main_pname$dat1";
mkdir $load_report_path/$new_folder
load_report_path=$load_report_path/$new_folder

main_load=$main_pname;
echo ""


#subroutine for user input handling. how many products do you want
chose_no_of_prdcts () {
	echo -n "From the above list how many products do you want run: "; 
	read u_total_product; 
	if [ $u_total_product -le $total_product -a $u_total_product -gt 0 ] 2>/dev/null
        then
                :
        else
                echo "Invalid Entry";
                chose_no_of_prdcts;
        fi
}
chose_no_of_prdcts;

echo ""; echo "";
echo "Choose the products and its order of execution. You will be prompted $u_total_product times"
echo "";



for (( i=1; i<=$u_total_product; i++ )) 
do
#subroutine for user input handlin in geting order of product.
  get_order_of_prdct () {
  	echo -n "Enter the product S.No number: "
  	read prdct_order;
  	if [ $prdct_order -le $total_product -a $prdct_order -gt 0 ] 2>/dev/null
        then
                :
        else
                echo "Invalid Entry";
                get_order_of_prdct;
        fi
  }
  get_order_of_prdct
  exec_order[$i]=${product_array[$prdct_order]};
done



echo ""; echo "";
echo "Order of execution is: ";

for i in "${exec_order[@]}"
do
	echo $i; 
done

#Obtaining the number of instance from user
n=1;
for i in "${exec_order[@]}"
do
  for j in {1..90}
  do
  eval m=\$product_name_$j
    if [ "$i" == "$m" ]
    then
        eval k=\${#product_$j[*]}
        echo ; echo ;
        echo "The product $i has $k instances"
	#Obtaining user input and validating it for instances
	get_no_of_instances () {
        	echo -n "How many instances do you want to run: "
        	read  nof_inst[$n]; 
		if [ ${nof_inst[$n]} -le $k -a ${nof_inst[$n]} -gt 0 ] 2>/dev/null
        	then
	     		:
		else
			echo "Invalid Entry";
	     		get_no_of_instances;
 		fi
	}
	get_no_of_instances;





    #subroutine for user input handling. capture tcap measurements and memory utilization for all products
    stats_user_inputs () {
            echo -n "Do you want to capture memory utilization (prstat and iostat) ? [y/n]: ";
            read stats[$n];
            if [ ${stats[$n]} = "Y" -o ${stats[$n]} = "y" -o ${stats[$n]} = "n" -o ${stats[$n]} = "N" ] 2>/dev/null
            then
                    :
            else
                    echo "Invalid Entry";
                    stats_user_inputs;
            fi
    }
    stats_user_inputs;

    if [ ${stats[$n]} = "Y" -o ${stats[$n]} = "y" ]
    then
            tcap_measurments () {
                            echo -n "Do you want to capture tcap measurements ? [y/n]: ";
                            read tcap_inputs[$n];
                            if [ ${tcap_inputs[$n]} = "Y" -o ${tcap_inputs[$n]} = "y" -o ${tcap_inputs[$n]} = "n" -o ${tcap_inputs[$n]} = "N" ] 2>/dev/null
                            then
                                    :
                            else
                                    echo "Invalid Entry";
                                    tcap_measurments;
                            fi
                    }
                    tcap_measurments;
    fi




	#Obtaining user input and validating it for log handling
	get_log_handl_data () {
        	printf "Choose the action on logs created by $i : \n 1. Delete \n 2. zip \n 3. Move \n 4. Do Nothing \n" 
        	echo -n "Enter the number : " 
        	read log_flag[$n];
		if [ ${log_flag[$n]} -eq 1 -o ${log_flag[$n]} -eq 2 -o ${log_flag[$n]} -eq 3  -o ${log_flag[$n]} -eq 4 ] 2>/dev/null
		then
			:
		else
			echo ; echo;
			echo "Invalid Entry"; echo ;
			get_log_handl_data;
		fi
	}
	get_log_handl_data;

        break;
    fi      
  done
n=`expr $n + 1`;
done




#########################################################
#Starting the instances and checking whether it already exists
#########################################################

#overlap handling function
overlap_handling () {

echo -n "What do you want to perform?
1. kill the running application
2. Exit

Press the corresponding number [1/2] : "

read yb ;
echo  -e "\n \n" >> $load_report_path/Load_Report_$main_load-$t.txt
echo "$1 is already running....." >> $load_report_path/Load_Report_$main_load-$t.txt 
echo "entered value is $yb ";
case $yb in
"1") overlap_inst_pid=`ptree | grep -v grep | grep -w "$1" | awk {'print $1'}`;
  echo -e "Killing  $1 with process id $overlap_inst_pid \n \n";
  echo -e "Killing  $1 with process id $overlap_inst_pid \n \n" >> $load_report_path/Load_Report_$main_load-$t.txt 
  kill -9 $overlap_inst_pid;;
"2") echo -e "\n \n \n Press Ctrl+c to exit "; while true; do echo "Press Ctrl+c to exit"; sleep 10; done;;
*) echo -e "invalid entry \n \n "; overlap_handling;;
esac
}


echo "################################"  >> $load_report_path/Load_Report_$main_load-$t.txt
echo "Load report for $main_load" >> $load_report_path/Load_Report_$main_load-$t.txt
echo "################################"  >> $load_report_path/Load_Report_$main_load-$t.txt
echo "" >> $load_report_path/Load_Report_$main_load-$t.txt
echo "Load started at $(date) with process id: $$" >> $load_report_path/Load_Report_$main_load-$t.txt
echo "=================================="  >> $load_report_path/Load_Report_$main_load-$t.txt
echo "" >> $load_report_path/Load_Report_$main_load-$t.txt

if [ -z $lag ]
then
     echo -e "\n \n No lag defined in config file. Taking default value 5 ";
     echo "###################################################";
     echo "Dont forget to assign a value for lag in the loadconf.sh file next time you run the load script";
     echo -e "################################################### \n \n";
     lag=5;

fi

if [ -z $restart_flag ]
then
     echo -e "\n \n No restart_flag defined in config file. Taking default value 1 ";
     echo "###################################################";
     echo "Dont forget to assign a value for restart_flag in the loadconf.sh file next time you run the load script";
     echo -e "################################################### \n \n";
     restart_flag=1;

fi

if [ -z $sos_logs ]
then
     echo -e "\n \n No sos_logs defined in config file. Taking default value 10 ";
     echo "###################################################";
     echo "Dont forget to assign a value for sos_logs in the loadconf.sh file next time you run the load script";
     echo -e "################################################### \n \n";
     sos_logs=10;
fi

#checking and starting instances
n=1;
for i in "${exec_order[@]}"
do
  for j in {1..90}
  do
  eval m=\$product_name_$j
    if [ "$i" == "$m" ]
    then
       echo ; echo "As per your input $i will run ${nof_inst[$n]} instance(s)"; 
       echo "================================================================";
       echo ; echo "As per user input $i will run ${nof_inst[$n]} instance(s)" >> $load_report_path/Load_Report_$main_load-$t.txt 
       o=${nof_inst[$n]};
       for (( o=1; o<=${nof_inst[$n]}; o++ ))
       do
          eval instance=\${product_$j[$o]}; #echo $instance;
          eval instance_path=\${product_path_$j[$o]}; #echo $instance_path;
          eval instance_start=\${product_start_$j[$o]}; #echo $instance_start;
          eval instance_log=\${product_log_$j[$o]}; #echo $instance_log;
          eval instance_logical_name=\${product_logicalname_$j[$o]}; #echo $instance_logical_name;
	  eval instance_move_log_to=\${product_move_log_to_$j[$o]};
	  #Validating the path and file existence
	  if [ -d $instance_path ]
	  then 
		if [ ! -f $instance_path/$instance_start ]
		then
			echo "Startup script not found. $instance_path/$instance_start ";
			echo "Hit ctrl+c to stop the script";
			echo "Startup script not found. $instance_path/$instance_start " >> $load_report_path/Load_Report_$main_load-$t.txt
			while true; do sleep 10; done
		fi
	   else
		echo "Path not found. $instance_path ";
                echo "Hit ctrl+c to stop the script";
		echo "Path not found. $instance_path " >> $load_report_path/Load_Report_$main_load-$t.txt
                while true; do sleep 10; done
	   fi
	
	  if [ ! -d $instance_log ]
	  then
		echo "Log path not found. $instance_log ";
                echo "Hit ctrl+c to stop the script";
                echo "Path not found. $instance_log " >> $load_report_path/Load_Report_$main_load-$t.txt
                while true; do sleep 10; done
           fi   

#Validating log moving path
if [ ${log_flag[$n]} -eq 3 ]
then
	  if [ -z $instance_move_log_to ]
	  then
                echo "Log action set to move but moving path not found for $i instance: $instance  " | tee -a $load_report_path/Load_Report_$main_load-$t.txt
		echo "Check the configuration file";
                echo "Hit ctrl+c to stop the script";
                while true; do sleep 10; done
           fi
          if [ ! -d $instance_move_log_to ]
          then
                echo "Log moving path not found. $instance_move_log_to ";
                echo "Hit ctrl+c to stop the script";
                echo "Path not found. $instance_move_log_to " >> $load_report_path/Load_Report_$main_load-$t.txt
                while true; do sleep 10; done
           fi  
fi
		 
          ptree | grep -v grep | grep -w "$instance";
          if [ $? -eq 0 ]
  	  then
              echo "Oops instance $instance is already running"; echo ;
              overlap_handling $instance;
          fi
          echo "Starting instance $instance for product $i";
          cd $instance_path;
          ./$instance_start > /dev/null & 
          cd $curr_path;
          
          sleep 2;
       done
       break;
    fi
  done
n=`expr $n + 1`;

#wait before starting next product
echo -e "\n \nWaiting $lag seconds before starting the next product" 
for (( r=1; r<=$lag; r++ ))
do
  sleep 1;
  sub_count=`expr $lag - $r`;
  echo -e "count down -->  $sub_count  \r\c"
done
echo ""
done

#sleep for sometime after starting all the products
delay (){
echo -e "Waiting for the all application's to stabilize...\c"
for (( r=1; r<=$1; r++ ))
do
  sleep 1;
  echo -e ".\c"
done
echo ""
}
delay 5;


#Obtaining the process id

n=1;
for i in "${exec_order[@]}"
do
  for j in {1..90}
  do
  eval m=\$product_name_$j
    if [ "$i" == "$m" ]
    then
       o=${nof_inst[$n]};
       for (( o=1; o<=${nof_inst[$n]}; o++ ))
       do
          eval instance=\${product_$j[$o]}; #echo $instance;
          eval instance_path=\${product_path_$j[$o]}; #echo $instance_path;
          eval instance_start=\${product_start_$j[$o]}; #echo $instance_start;
          eval instance_log=\${product_log_$j[$o]}; #echo $instance_log;
          eval instance_logical_name=\${product_logicalname_$j[$o]}; #echo $instance_logical_name;
          eval inital_inst_pid_$j[$o]=`ptree | grep -v grep | grep -w "$instance" | awk {'print $1'}`;
          eval tmid=\${inital_inst_pid_$j[$o]};
          restart_count=1;
          if [ -z $restart_limit ]
          then
               echo -e "\n \n No restart limit defined in config file. Taking default value 3 ";
	       echo "###################################################";
	       echo "Dont forget to assign a value for restart_limit in the loadconf.sh file next time you run the load script";
               echo -e "################################################### \n \n";
               restart_limit=3;
          fi

          restart_instance_empty_pid () {
          	if [ -z "$tmid" ]; 
	  	then
			echo ; echo ; echo;
              		echo "OOPS.. No process id found. Probably causes are:";
			echo "1.  you entered wrong bin name for grep of processid";
			echo "2.  you entered wrong start script path name";
			echo "3.  The application is not coming up";
              		echo "check the instance $instance is correctly defined under $i";
	      		echo "Trying to restart the instance $instance ";
			echo "########################################";
			echo "   Restarting.... Attempt: $restart_count ";
                        echo "########################################";
			echo "OOPS.. No process id found. Trying to restart the instances $instance. Attempt $restart_count" >> $load_report_path/Load_Report_$main_load-$t.txt
              		cd $instance_path;
              		./$instance_start > /dev/null &
              		cd $curr_path;
	      		eval inital_inst_pid_$j[$o]=`ptree | grep -v grep | grep -w "$instance" | awk {'print $1'}`;
              		eval tmid=\${inital_inst_pid_$j[$o]};
                        if [ $restart_count -ge $restart_limit ]
                        then
                                echo "Restart attempts exceeded the limit"
                                echo "Hit Ctrl+C to stop the script..."
                                while true
                                do
                                  echo "";
                                  echo "#################################";
				  echo "Error occured... No process id found for instance $instance";
                                  echo "Hit Ctrl+C to stop the script...";
				  echo "Note: If Ctrl+C is not working then press ctrl+d and then hit ctrl+c ";
                                  echo "#################################";
				  echo "Error occured... No process id found for instance $instance" >> $load_report_path/Load_Report_$main_load-$t.txt
				  echo "Script will not proceed further." >> $load_report_path/Load_Report_$main_load-$t.txt 
                                  sleep 5
                                done
                        fi
                        restart_count=`expr $restart_count + 1`;
              		if [ -z "$tmid" ];
              		then
 				sleep 5;
		   		restart_instance_empty_pid;
              		else
                   		echo "Restart was successful";
              		fi
	   		fi
	   }
	  restart_instance_empty_pid;
          echo  "Process id of $i instance $instance is: $tmid";
	  echo  "Process id of $i instance $instance is: $tmid" >> $load_report_path/Load_Report_$main_load-$t.txt
          cd $instance_path;
         # ./$instance_start > /dev/null &
          cd $curr_path;

          sleep 2;
       done
       break;
    fi
  done
n=`expr $n + 1`;
done


#Log handling

delete_log () {
	count=`ls -Ftr | grep -v '/' | egrep ".log|.tdr" | wc -l`
	count1=`expr $count - $keep_files`;
	while [ $count1 -gt 0 ]
	do
		ls -Frt | egrep ".log|.tdr" | grep -v '/' | head -"$count1" | xargs rm -rf 2>/dev/null
		echo "log files deleted from the path $instance_log1 ";
                count=`ls -Ftr | grep -v '/' | egrep ".log|.tdr" | wc -l`;
		count1=`expr $count - $keep_files`;
	done
}

move_logs () {
        count=`ls -Ftr | grep -v '/' | egrep ".log|.tdr" | wc -l`
        count1=`expr $count - $keep_files`;
        while [ $count1 -gt 0 ]
        do
                ftbm=`ls -Frt | egrep ".log|.tdr" | grep -v '/' | head -"$count1"` 
		echo -e "\nFile(s) :  ";
		echo -e "========";
		for each_files in $ftbm
		do
		  printf "$each_files" 
		done
                echo -e "\nare being moved: \nFrom: $instance_log1 \nTo: $instance_move_log_to1 \n";
		mv  $ftbm $instance_move_log_to1
                count=`ls -Ftr | grep -v '/' | egrep ".log|.tdr" | wc -l`;
                count1=`expr $count - $keep_files`;
        done
}


gzip_log () {
        count=`ls -Ftr | grep -v '/' | egrep ".log|.tdr" | wc -l`;
	count1=`expr $count - $keep_unzip_files`;
	while [ $count1 -gt 0 ]
	do
		tbz=`ls -Frt | grep -v '/' | grep -v gz | head -"$count1"`;
		for filename in $tbz
		do
			[[ -d Gzip ]] || mkdir Gzip
			mv $filename Gzip
			cd Gzip
			gzip $filename &
			cd ..
			echo "gzipped the file: $filename from the path $instance_log1 "
		done
                count=`ls -Ftr | grep -v '/' | egrep ".log|.tdr" | wc -l`;
		count1=`expr $count - $keep_unzip_files`;
	done
}



log_handling () {
	while true
	do
        sleep 5;
	n1=1;
	for i1 in "${exec_order[@]}"
	do
		for j1 in {1..90}
		do
			eval m1=\$product_name_$j1
			if [ "$i1" == "$m1" ]
			then
				o1=${nof_inst[$n1]};
				for (( o1=1; o1<=${nof_inst[$n1]}; o1++ ))
				do
					eval instance1=\${product_$j1[$o1]}; 
					eval instance_log1=\${product_log_$j1[$o1]};   
                                        eval instance_move_log_to1=\${product_move_log_to_$j1[$o1]};
					cd $instance_log1;
					if [ ${log_flag[$n1]} -eq 1 ]
					then 
						delete_log;
					elif [ ${log_flag[$n1]} -eq 2 ]
					then
						gzip_log;
                                        elif [ ${log_flag[$n1]} -eq 3 ]
                                        then
                                                move_logs;
					else
						:
					fi
				cd $curr_path
				sleep 2;
				done
				break;
			fi
		done
		n1=`expr $n1 + 1`;
	done

	done
}

log_handling &


#calculating the number of instance for the main product
#entered by the user

main_prdct_inst=1;
for c1 in "${exec_order[@]}"
do
  eval main_prdct_name=\${product_name_$k1};
  if [ $main_prdct_name = $c1 ]
  then 
	g=${nof_inst[$main_prdct_inst]}
	break;
  else
	:
        main_prdct_inst=`expr $main_prdct_inst + 1`;
  fi
done


#statistics computation
#The arguments taken by these functions are:
#one_min_stats product_name no_of_instances array_no product_no
#one_min_stats $m1 $o1 $n1 $j1
#one_hour_stats product_name no_of_instances array_no product_no
#one_hour_stats $m1 $o1 $n1 $j1

one_min_stats () {
n2=1
while true
do
	
	for (( a=1; a<=$2; a++ ))
	do
		eval instance2=\${product_$4[$a]};
		eval instance_logical_name2=\${product_logicalname_$4[$a]};
		eval stack=\${stack_$4[$a]};
		live_tmp2=(`ptree | grep -v grep | grep -w "$instance2" | awk {'print $1'}`);
                ps -lyef | egrep -i "$instance2|UID" | egrep -v 'grep|vi'| nawk '$3=="PID" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }' | tr -s ' ' ',' | grep -w $instance2 | cut -d, -f1,3-5,9-10,14-16 >> $load_report_path/${1}_Minutes_Ps_Mem_${t}.csv
		prstat -p $live_tmp2 60 1 | nawk '$1=="PID" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| grep -w "$instance2" | tr -s ' ' ',' >> $load_report_path/${1}_Minutes_Prstat_Cpu_Mem_${t}.csv
 
		if [ ${tcap_inputs[$3]} = "y" -o ${tcap_inputs[$3]} = "Y" ]
		then
			echo "Writing tcapmeasd in the file  ${1}_TCAPmeasd_${t}.log ";
			echo "=======================================================" >> $load_report_path/${1}_TCAPmeasd_${t}.log
            date >> $load_report_path/${1}_TCAPmeasd_${t}.log;
            echo "=======================================================" >> $load_report_path/${1}_TCAPmeasd_${t}.log
			SHM=100;
			prd_inst=`printf "%.5d" "$live_tmp2"`;
			/opt/ulcm/bin/tcaplmeasd ITU $stack ${instance_logical_name2}${prd_inst} >> $load_report_path/${1}_TCAPmeasd_${t}.log
		fi
    done
	sleep 60;
   n2=`expr $n2 + 1`;
done
}

one_min_server_stats () {
echo "Date_time,time,usr,sys,wio,idle" >> $load_report_path/${1}_Minutes_Server_Sar_Cpu_Statistics_${t}.csv
echo "Date_time,processes,lwps,load averages: 1 min, 5 min, 15 min" >> $load_report_path/${1}_Minutes_Server_LoadAverage_Statistics_${t}.csv
echo "Date_time,r/s,w/s,kr/s,kw/s,wait,actv,wsvc_t,asvc_t,%w,%b,device,partition" >> $load_report_path/${1}_Minutes_Server_IOstat_Statistics_${t}.csv
echo "Date_time,r,b,w,swap,free,re,mf,pi,po,fr,de,sr,s0,s1,s2,s3,in,sy,cs,us,sy,id" >> $load_report_path/${1}_Minutes_Server_VMstat_Statistics_${t}.csv
echo "Date_time,SET,minf,mjf,xcal,intr,ithr,csw,icsw,migr,smtx,srw,syscl,usr,sys,wt,idl,sze" >> $load_report_path/${1}_Minutes_Server_MPstat_Statistics_${t}.csv
echo "Date_time,Name,Mtu,Net/Dest,Address,Ipkts,Ierrs,Opkts,Oerrs,Collis,Queue," >> $load_report_path/${1}_Minutes_Server_Netstat_Statistics_${t}.csv
n4=1
echo "disk_partition_count=$disk_partition_count"
while true
do
	        momque=`ls -lrt $momq_path |tail -1|awk '{ print $9}'`
		echo "" >> $load_report_path/${1}_Minutes_Stack_MomQueue_Statistics_${t}.log
		echo -e "\n MOMQUE report:" >> $load_report_path/${1}_Minutes_Stack_MomQueue_Statistics_${t}.log
		echo "---------------" >> $load_report_path/${1}_Minutes_Stack_MomQueue_Statistics_${t}.log
		echo "************Filename=$momque *******************" >>  $load_report_path/${1}_Minutes_Stack_MomQueue_Statistics_${t}.log
                grep -i "MOM" $momq_path/$momque | tail -1 >>  $load_report_path/${1}_Minutes_Stack_MomQueue_Statistics_${t}.log
		echo "------------" >> $load_report_path/${1}_Minutes_Stack_MomQueue_Statistics_${t}.log

                sar -u 1 2|egrep -v '^$|SunOS|Average' | nawk '$2=="%usr" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " ","|sed '$!d' >> $load_report_path/${1}_Minutes_Server_Sar_Cpu_Statistics_${t}.csv
                prstat 60 1 | grep -w 'load averages:'|nawk '$1=="Total:" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," | cut -d, -f1,3,5,9-11 >> $load_report_path/${1}_Minutes_Server_LoadAverage_Statistics_${t}.csv
                iostat -xnzrmp 1 2 | nawk '$1=="extended" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," | egrep -v 'device' | awk 'NR==17,NR==$NR {print}' >> $load_report_path/${1}_Minutes_Server_IOstat_Statistics_${t}.csv
                vmstat 1 2 | nawk '$1=="kthr" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," |sed '$!d' >> $load_report_path/${1}_Minutes_Server_VMstat_Statistics_${t}.csv
                mpstat -a 1 5 |nawk '$1=="SET" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " ","|sed '$!d' >> $load_report_path/${1}_Minutes_Server_MPstat_Statistics_${t}.csv
                netstat -in |egrep -v '^$'|nawk '$1=="Name" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," | egrep -v 'Name' >> $load_report_path/${1}_Minutes_Server_Netstat_Statistics_${t}.csv
	sleep 60;
   n4=`expr $n4 + 1`;
done
}


########## One Hour Application Stats ###################
one_hour_stats () {
n3=1
while true
do
	
	for (( a3=1; a3<=$2; a3++ ))
	do
		eval instance3=\${product_$4[$a3]};
		eval instance_logical_name3=\${product_logicalname_$4[$a3]};
		live_tmp3=(`ptree | grep -v grep | grep -w "$instance3" | awk {'print $1'}`);
                ps -lyef | egrep -i "$instance3|UID" | egrep -v 'grep|vi'| nawk '$3=="PID" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }' | tr -s ' ' ',' | grep -w $instance3 | cut -d, -f1,3-5,9-10,14-16 >> $load_report_path/${1}_Hourly_Ps_Mem_${t}.csv
		prstat -p $live_tmp3 60 1 | nawk '$1=="PID" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| grep -w "$instance3" | tr -s ' ' ',' >> $load_report_path/${1}_Hourly_Prstat_Cpu_Mem_${t}.csv
 
    done

   sleep 3600;
   n3=`expr $n3 + 1`;
done
}

########## END of One Hour Application Stats ###################

########## One Hour Server Stats ###################
one_hour_server_stats () {
echo "Date_time,time,usr,sys,wio,idle" >> $load_report_path/${1}_Hourly_Server_Sar_Cpu_Statistics_${t}.csv
echo "Date_time,processes,lwps,load averages: 1 min, 5 min, 15 min" >> $load_report_path/${1}_Hourly_Server_LoadAverage_Statistics_${t}.csv
echo "Date_time,r/s,w/s,kr/s,kw/s,wait,actv,wsvc_t,asvc_t,%w,%b,device,partition" >> $load_report_path/${1}_Hourly_Server_IOstat_Statistics_${t}.csv
echo "Date_time,r,b,w,swap,free,re,mf,pi,po,fr,de,sr,s0,s1,s2,s3,in,sy,cs,us,sy,id" >> $load_report_path/${1}_Hourly_Server_VMstat_Statistics_${t}.csv
echo "Date_time,SET,minf,mjf,xcal,intr,ithr,csw,icsw,migr,smtx,srw,syscl,usr,sys,wt,idl,sze" >> $load_report_path/${1}_Hourly_Server_MPstat_Statistics_${t}.csv
echo "Date_time,Name,Mtu,Net/Dest,Address,Ipkts,Ierrs,Opkts,Oerrs,Collis,Queue," >> $load_report_path/${1}_Hourly_Server_Netstat_Statistics_${t}.csv
n5=1
echo "disk_partition_count=$disk_partition_count"
while true
do

                sar -u 1 2|egrep -v '^$|SunOS|Average' | nawk '$2=="%usr" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " ","|sed '$!d' >> $load_report_path/${1}_Hourly_Server_Sar_Cpu_Statistics_${t}.csv
                prstat 60 1 | grep -w 'load averages:'|nawk '$1=="Total:" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," | cut -d, -f1,3,5,9-11 >> $load_report_path/${1}_Hourly_Server_LoadAverage_Statistics_${t}.csv
                iostat -xnzrmp 1 2 | nawk '$1=="extended" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," | egrep -v 'device' | awk 'NR==17,NR==$NR {print}' >> $load_report_path/${1}_Hourly_Server_IOstat_Statistics_${t}.csv
                vmstat 1 5 | nawk '$1=="kthr" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," |sed '$!d' >> $load_report_path/${1}_Hourly_Server_VMstat_Statistics_${t}.csv
                mpstat -a 1 5 |nawk '$1=="SET" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " ","|sed '$!d' >> $load_report_path/${1}_Hourly_Server_MPstat_Statistics_${t}.csv
                netstat -in |egrep -v '^$'|nawk '$1=="Name" { "date '+%Y-%m-%d_%H:%M:%S'" | getline d ; close("date") } { print d,$0 }'| tr -s " " "," | egrep -v 'Name' >> $load_report_path/${1}_Hourly_Server_Netstat_Statistics_${t}.csv
	sleep 3600;
   n5=`expr $n5 + 1`;
done
}

########## End of One Hour Server Stats ###################




#################### Handle stats and Tcap for all products ######################3
stats_handling () {
        one_hour_server_stats $Server_Name &
        one_min_server_stats $Server_Name &
        n1=1;
        for i1 in "${exec_order[@]}"
        do

                for j1 in {1..90}
                do
                        eval m1=\$product_name_$j1
                        if [ "$i1" == "$m1" ]
                        then
                                o1=${nof_inst[$n1]};
								if [ ${stats[$n1]} = "y" -o ${stats[$n1]} = "Y" ]
                                then
                                      echo "Date_time,UID,PID,PPID,RSS,SZ,TIME,CMD" >> $load_report_path/${m1}_Minutes_Ps_Mem_${t}.csv
                                      echo "Date_time,PID,USERNAME,SIZE,RSS,STATE,PRI,NICE,TIME,CPU,PROCESS/NLWP" >> $load_report_path/${m1}_Minutes_Prstat_Cpu_Mem_${t}.csv
                                      echo "Date_time,UID,PID,PPID,RSS,SZ,TIME,CMD" >> $load_report_path/${m1}_Hourly_Ps_Mem_${t}.csv
                                      echo "Date_time,PID,USERNAME,SIZE,RSS,STATE,PRI,NICE,TIME,CPU,PROCESS/NLWP" >> $load_report_path/${m1}_Hourly_Prstat_Cpu_Mem_${t}.csv
								      one_hour_stats $m1 $o1 $n1 $j1 &
								      one_min_stats $m1 $o1 $n1 $j1 &
								fi
                                break;
                        fi
                done
                n1=`expr $n1 + 1`;
       done
}
stats_handling

################### End of stats and Tcap handling for all products ##################3



stop_load &

#Maintain the process

while true
do

 n=1;
for i in "${exec_order[@]}"
do
  for j in {1..90}
  do
  eval m=\$product_name_$j
    if [ "$i" == "$m" ]
    then
       for (( o=1; o<=${nof_inst[$n]}; o++ ))
       do
          eval instance=\${product_$j[$o]}; #echo $instance;
          eval instance_path=\${product_path_$j[$o]}; #echo $instance_path;
          eval instance_start=\${product_start_$j[$o]}; #echo $instance_start;
          eval instance_log=\${product_log_$j[$o]}; #echo $instance_log;
          eval instance_logical_name=\${product_logicalname_$j[$o]}; #echo $instance_logical_name;
          live_tmp=(`ptree | grep -v grep | grep -w "$instance" | awk {'print $1'}`);
          eval live_pid_$j[$o]=\$live_tmp;
          eval inital_pid=\${inital_inst_pid_$j[$o]};
          live_pid=$live_tmp;
          if [ $inital_pid -eq $live_tmp ] 2>/dev/null
          then
              echo "product $i instance $instance is alive with pid: $live_pid";
          else
              echo "product $i instance $instance is alive with pid: $live_pid";
              echo "Oops instance $instance is dead................"; echo ;
	      echo -e "\n \n" >> $load_report_path/Load_Report_$main_load-$t.txt
              echo "Instance $instance is dead at $(date)" >> $load_report_path/Load_Report_$main_load-$t.txt

	      #Saving the logs
	      sos_time=$(date +"%m-%d-%Y-%T")
	      mkdir $load_report_path/SOS_Logs_$sos_time
	      echo "copying the last $sos_logs log files to the directory SOS_Logs_$sos_time  " | tee -a  $load_report_path/Load_Report_$main_load-$t.txt
	      cpath=`pwd`;
	      cd $instance_log;
	      cp `ls -rtl | grep -v '^d' | tail -$sos_logs | awk {'print $9'}` $load_report_path/SOS_Logs_$sos_time 
	      echo "Logs are successfully copied";
	      cd $cpath;
	      if [ $restart_flag -eq 1 ]
	      then 
			:
	      else
			echo "Application went down..." | tee -a $load_report_path/Load_Report_$main_load-$t.txt
			echo " No restart flag enabled... Hit Ctrl+C to exit" | tee -a $load_report_path/Load_Report_$main_load-$t.txt
			while true; do sleep 10; done 
	      fi

              echo "Restarting instance $instance for product $i";
              echo "Restarting instance $instance for product $i" >> $load_report_path/Load_Report_$main_load-$t.txt
	      sleep $lag;
              cd $instance_path;
              ./$instance_start > /dev/null &
              cd $curr_path;
              delay 5;
              live_pid=`ptree | grep -v grep | grep -w "$instance" | awk {'print $1'}`;
              eval inital_inst_pid_$j[$o]=$live_pid;
              echo "$instance for product $i is now up and running with process id: $live_pid ";
              echo "$instance for product $i is now up and running at $(date) with process id: $live_pid " >> $load_report_path/Load_Report_$main_load-$t.txt
          fi

          sleep 2;
       done
       break;
    fi
  done
  echo "========================================================================";
 n=`expr $n + 1`;
 done

done
